
<?php if ($posts = $this->getRecent()): ?>
<div class="block block-blog-recent">
    <div class="block-content">
        <div>
        <?php foreach ($posts as $post): ?>
            <div class="recent-post-mini">
                
                <?php
                    if($post_image = $post->getImage()){
                ?>
                <a class="postimg" href="<?php echo $post->getAddress(); ?>" title="<?php echo $post->getTitle(); ?>">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post_image; ?>" alt=""/>
                </a>
                <?php
                    }
                ?>
                <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
                <br><?php echo $this->__('by ')?><strong><?php echo $post->getUser() ?></strong>
                <br><?php echo date('d M Y', strtotime($post->getCreatedTime())) ?>
                <div class="clearfix"></div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>    
</div>
<?php endif; ?>

<?php echo $this->getChildHtml('blog_tags'); ?>
